include: antmicro-pcb-release-ci-template@main:.pcb-repo-ci.yml
variables: 
  HRAFN_ISSUE_ID: 94406
  BLENDER_MODELS_BRANCH: components/95534-RD-add-RV09AF
  KICAD_COMPONENTS_BRANCH: components/95534-RD-add-RV09AF